const districtData = {
  "Adilabad": {
    "name": "Adilabad",
    "telugu": "ఆదిలాబాద్",
    "rainfall": "1100 mm",
    "rainfall_te": "1100 మి.మీ.",
    "temperature": "28°C",
    "temperature_te": "28 డిగ్రీల సెల్సియస్",
    "soil": "Black cotton soil",
    "soil_te": "నల్లపాటి మట్టి",
    "crops": "Cotton, Turmeric, Soybean",
    "crops_te": "పత్తి, పసుపు, సోయాబీన్",
    "humidity": "70%",
    "humidity_te": "70%",
    "ph": "6.8",
    "ph_te": "6.8",
    "water": "Godavari, Purna",
    "water_te": "గోదావరి, పూర్ణా",
    "fertilizers": "Urea, Potash",
    "fertilizers_te": "యూరియా, పొటాష్",
    "irrigation": "Canal, Bore well",
    "irrigation_te": "కాలువలు, బోర్ వెల్"
  },
  "Bhadradri Kothagudem": {
    "name": "Bhadradri Kothagudem",
    "telugu": "భద్రాద్రి కొత్తగూడెం",
    "rainfall": "1200 mm",
    "rainfall_te": "1200 మి.మీ.",
    "temperature": "29°C",
    "temperature_te": "29 డిగ్రీల సెల్సియస్",
    "soil": "Red loamy soil",
    "soil_te": "ఎరుపు లోమీ మట్టి",
    "crops": "Paddy, Chillies, Cotton",
    "crops_te": "బియ్యం, మిరప, పత్తి",
    "humidity": "75%",
    "humidity_te": "75%",
    "ph": "6.3",
    "ph_te": "6.3",
    "water": "Godavari",
    "water_te": "గోదావరి",
    "fertilizers": "DAP, MOP",
    "fertilizers_te": "డి.ఏ.పీ, ఎం.ఓ.పీ",
    "irrigation": "Lift, Canal",
    "irrigation_te": "లిఫ్ట్, కాలువ"
  },
  "Hanumakonda": {
    "name": "Hanumakonda",
    "telugu": "హనుమకొండ",
    "rainfall": "900 mm",
    "rainfall_te": "900 మి.మీ.",
    "temperature": "31°C",
    "temperature_te": "31 డిగ్రీల సెల్సియస్",
    "soil": "Loamy soil",
    "soil_te": "లోమీ మట్టి",
    "crops": "Paddy, Maize, Cotton",
    "crops_te": "బియ్యం, మక్కజొన్న, పత్తి",
    "humidity": "60%",
    "humidity_te": "60%",
    "ph": "6.6",
    "ph_te": "6.6",
    "water": "Pakhal Lake",
    "water_te": "పాఖల సరస్సు",
    "fertilizers": "Urea, Super Phosphate",
    "fertilizers_te": "యూరియా, సూపర్ ఫాస్ఫేట్",
    "irrigation": "Canal, Tanks",
    "irrigation_te": "కాలువలు, చెరువులు"
  },
  "Hyderabad": {
    "name": "Hyderabad",
    "telugu": "హైదరాబాద్",
    "rainfall": "800 mm",
    "rainfall_te": "800 మి.మీ.",
    "temperature": "33°C",
    "temperature_te": "33 డిగ్రీల సెల్సియస్",
    "soil": "Red sandy soil",
    "soil_te": "ఎరుపు ముంచి మట్టి",
    "crops": "Vegetables, Flowers",
    "crops_te": "కూరగాయలు, పుష్పాలు",
    "humidity": "55%",
    "humidity_te": "55%",
    "ph": "6.5",
    "ph_te": "6.5",
    "water": "Himayat Sagar, Osman Sagar",
    "water_te": "హిమాయత్ సాగర్, ఉస్మాన్ సాగర్",
    "fertilizers": "Organic compost, Urea",
    "fertilizers_te": "జైవ ఎరువులు, యూరియా",
    "irrigation": "Drip, Bore well",
    "irrigation_te": "డ్రిప్, బోర్ వెల్"
  },
  "Jagtial": {
    "name": "Jagtial",
    "telugu": "జగిత్యాల",
    "rainfall": "950 mm",
    "rainfall_te": "950 మి.మీ.",
    "temperature": "30°C",
    "temperature_te": "30 డిగ్రీల సెల్సియస్",
    "soil": "Black soil",
    "soil_te": "నల్ల మట్టి",
    "crops": "Paddy, Maize, Groundnut",
    "crops_te": "బియ్యం, మక్కజొన్న, వరి పల్లి",
    "humidity": "65%",
    "humidity_te": "65%",
    "ph": "6.7",
    "ph_te": "6.7",
    "water": "Maneru River",
    "water_te": "మనేరు నది",
    "fertilizers": "DAP, Urea",
    "fertilizers_te": "డి.ఏ.పీ, యూరియా",
    "irrigation": "Canal, Bore well",
    "irrigation_te": "కాలువలు, బోర్ వెల్"
  },
  "Jangaon": {
    "name": "Jangaon",
    "telugu": "జనగాం",
    "rainfall": "850 mm",
    "rainfall_te": "850 మి.మీ.",
    "temperature": "29°C",
    "temperature_te": "29 డిగ్రీల సెల్సియస్",
    "soil": "Sandy loam",
    "soil_te": "సంధి లోమ్ మట్టి",
    "crops": "Paddy, Cotton, Pulses",
    "crops_te": "బియ్యం, పత్తి, పప్పుధాన్యాలు",
    "humidity": "60%",
    "humidity_te": "60%",
    "ph": "6.4",
    "ph_te": "6.4",
    "water": "Local tanks, Borewells",
    "water_te": "చెరువులు, బోర్ వెల్లు",
    "fertilizers": "Urea, Potash",
    "fertilizers_te": "యూరియా, పొటాష్",
    "irrigation": "Bore well, Canal",
    "irrigation_te": "బోర్ వెల్, కాలువ"
  },
  "Jayashankar Bhupalpally": {
    "name": "Jayashankar Bhupalpally",
    "telugu": "జయశంకర్ భూపాలపల్లి",
    "rainfall": "1000 mm",
    "rainfall_te": "1000 మి.మీ.",
    "temperature": "30°C",
    "temperature_te": "30 డిగ్రీల సెల్సియస్",
    "soil": "Red and black soil",
    "soil_te": "ఎరుపు మరియు నల్ల మట్టి",
    "crops": "Cotton, Paddy, Maize",
    "crops_te": "పత్తి, బియ్యం, మక్కజొన్న",
    "humidity": "68%",
    "humidity_te": "68%",
    "ph": "6.6",
    "ph_te": "6.6",
    "water": "Godavari",
    "water_te": "గోదావరి",
    "fertilizers": "DAP, Super Phosphate",
    "fertilizers_te": "డి.ఏ.పీ, సూపర్ ఫాస్ఫేట్",
    "irrigation": "Canals, Bore wells",
    "irrigation_te": "కాలువలు, బోర్ వెల్లు"
  },
  "Jogulamba Gadwal": {
    "name": "Jogulamba Gadwal",
    "telugu": "జోగులాంబ గద్వాల",
    "rainfall": "700 mm",
    "rainfall_te": "700 మి.మీ.",
    "temperature": "32°C",
    "temperature_te": "32 డిగ్రీల సెల్సియస్",
    "soil": "Red loamy soil",
    "soil_te": "ఎరుపు లోమీ మట్టి",
    "crops": "Cotton, Jowar, Groundnut",
    "crops_te": "పత్తి, జొన్న, వేరుశెనగ",
    "humidity": "55%",
    "humidity_te": "55%",
    "ph": "6.2",
    "ph_te": "6.2",
    "water": "Krishna River",
    "water_te": "కృష్ణా నది",
    "fertilizers": "Potash, Urea",
    "fertilizers_te": "పొటాష్, యూరియా",
    "irrigation": "Bore wells, Canal",
    "irrigation_te": "బోర్ వెల్లు, కాలువ"
  },
  "Kamareddy": {
    "name": "Kamareddy",
    "telugu": "కమారెడ్డి",
    "rainfall": "950 mm",
    "rainfall_te": "950 మి.మీ.",
    "temperature": "28°C",
    "temperature_te": "28 డిగ్రీల సెల్సియస్",
    "soil": "Black soil",
    "soil_te": "నల్ల మట్టి",
    "crops": "Maize, Cotton, Paddy",
    "crops_te": "మక్కజొన్న, పత్తి, బియ్యం",
    "humidity": "68%",
    "humidity_te": "68%",
    "ph": "6.5",
    "ph_te": "6.5",
    "water": "Manjeera River",
    "water_te": "మంజీరా నది",
    "fertilizers": "Urea, DAP",
    "fertilizers_te": "యూరియా, డి.ఏ.పీ",
    "irrigation": "Canals, Tanks",
    "irrigation_te": "కాలువలు, చెరువులు"
  },
  "Karimnagar": {
    "name": "Karimnagar",
    "telugu": "కరీంనగర్",
    "rainfall": "920 mm",
    "rainfall_te": "920 మి.మీ.",
    "temperature": "31°C",
    "temperature_te": "31 డిగ్రీల సెల్సియస్",
    "soil": "Alluvial soil",
    "soil_te": "అల్యూవియల్ మట్టి",
    "crops": "Paddy, Cotton, Maize",
    "crops_te": "బియ్యం, పత్తి, మక్కజొన్న",
    "humidity": "66%",
    "humidity_te": "66%",
    "ph": "6.4",
    "ph_te": "6.4",
    "water": "Manair River",
    "water_te": "మనైర్ నది",
    "fertilizers": "Urea, Super Phosphate",
    "fertilizers_te": "యూరియా, సూపర్ ఫాస్ఫేట్",
    "irrigation": "Canals, Borewells",
    "irrigation_te": "కాలువలు, బోర్ వెల్లు"
  },
    "Khammam": {
      "name": "Khammam",
      "telugu": "ఖమ్మం",
      "rainfall": "1050 mm",
      "rainfall_te": "1050 మి.మీ.",
      "temperature": "30°C",
      "temperature_te": "30 డిగ్రీల సెల్సియస్",
      "soil": "Alluvial and Red soils",
      "soil_te": "అల్ల్యూవియల్ మరియు ఎరుపు మట్టి",
      "crops": "Paddy, Cotton, Chillies",
      "crops_te": "బియ్యం, పత్తి, మిరప",
      "humidity": "70%",
      "humidity_te": "70%",
      "ph": "6.7",
      "ph_te": "6.7",
      "water": "Godavari River",
      "water_te": "గోదావరి నది",
      "fertilizers": "Urea, MOP",
      "fertilizers_te": "యూరియా, ఎం.ఓ.పీ",
      "irrigation": "Canals, Tanks",
      "irrigation_te": "కాలువలు, చెరువులు"
    },
    "Komaram Bheem": {
      "name": "Komaram Bheem",
      "telugu": "కొమురం భీమ్ ఆసిఫాబాద్",
      "rainfall": "1150 mm",
      "rainfall_te": "1150 మి.మీ.",
      "temperature": "27°C",
      "temperature_te": "27 డిగ్రీల సెల్సియస్",
      "soil": "Black cotton soil",
      "soil_te": "నల్లపాటి మట్టి",
      "crops": "Turmeric, Cotton, Maize",
      "crops_te": "పసుపు, పత్తి, మక్కజొన్న",
      "humidity": "72%",
      "humidity_te": "72%",
      "ph": "6.8",
      "ph_te": "6.8",
      "water": "Penganga River",
      "water_te": "పెంగంగా నది",
      "fertilizers": "Urea, DAP",
      "fertilizers_te": "యూరియా, డి.ఏ.పీ",
      "irrigation": "Bore wells, Canal",
      "irrigation_te": "బోర్ వెల్లు, కాలువ"
    },
    "Mahabubabad": {
      "name": "Mahabubabad",
      "telugu": "మహబూబాబాద్",
      "rainfall": "950 mm",
      "rainfall_te": "950 మి.మీ.",
      "temperature": "29°C",
      "temperature_te": "29 డిగ్రీల సెల్సియస్",
      "soil": "Red loamy soil",
      "soil_te": "ఎరుపు లోమీ మట్టి",
      "crops": "Paddy, Cotton, Pulses",
      "crops_te": "బియ్యం, పత్తి, పప్పుధాన్యాలు",
      "humidity": "66%",
      "humidity_te": "66%",
      "ph": "6.5",
      "ph_te": "6.5",
      "water": "Local tanks",
      "water_te": "చెరువులు",
      "fertilizers": "Potash, Urea",
      "fertilizers_te": "పొటాష్, యూరియా",
      "irrigation": "Canals, Bore wells",
      "irrigation_te": "కాలువలు, బోర్ వెల్లు"
    },
    "Mahabubnagar": {
      "name": "Mahabubnagar",
      "telugu": "మహబూబ్ నగర్",
      "rainfall": "650 mm",
      "rainfall_te": "650 మి.మీ.",
      "temperature": "32°C",
      "temperature_te": "32 డిగ్రీల సెల్సియస్",
      "soil": "Red sandy soil",
      "soil_te": "ఎరుపు ముంచి మట్టి",
      "crops": "Jowar, Bajra, Cotton",
      "crops_te": "జొన్న, సజ్జ, పత్తి",
      "humidity": "50%",
      "humidity_te": "50%",
      "ph": "6.2",
      "ph_te": "6.2",
      "water": "Krishna River",
      "water_te": "కృష్ణా నది",
      "fertilizers": "DAP, Organic manure",
      "fertilizers_te": "డి.ఏ.పీ, సేంద్రీయ ఎరువులు",
      "irrigation": "Bore wells, Tanks",
      "irrigation_te": "బోర్ వెల్లు, చెరువులు"
    },
    "Mancherial": {
      "name": "Mancherial",
      "telugu": "మంచిర్యాల",
      "rainfall": "1000 mm",
      "rainfall_te": "1000 మి.మీ.",
      "temperature": "28°C",
      "temperature_te": "28 డిగ్రీల సెల్సియస్",
      "soil": "Black and red soils",
      "soil_te": "నల్ల మరియు ఎరుపు మట్టి",
      "crops": "Cotton, Turmeric, Maize",
      "crops_te": "పత్తి, పసుపు, మక్కజొన్న",
      "humidity": "65%",
      "humidity_te": "65%",
      "ph": "6.7",
      "ph_te": "6.7",
      "water": "Godavari River",
      "water_te": "గోదావరి నది",
      "fertilizers": "Urea, Potash",
      "fertilizers_te": "యూరియా, పొటాష్",
      "irrigation": "Canals, Bore wells",
      "irrigation_te": "కాలువలు, బోర్ వెల్లు"
    },
    "Medak": {
      "name": "Medak",
      "telugu": "మేదక్",
      "rainfall": "850 mm",
      "rainfall_te": "850 మి.మీ.",
      "temperature": "29°C",
      "temperature_te": "29 డిగ్రీల సెల్సియస్",
      "soil": "Red sandy loam",
      "soil_te": "ఎరుపు ముంచి లోమ్ మట్టి",
      "crops": "Maize, Paddy, Sunflower",
      "crops_te": "మక్కజొన్న, బియ్యం, సూర్యకాంతి",
      "humidity": "60%",
      "humidity_te": "60%",
      "ph": "6.5",
      "ph_te": "6.5",
      "water": "Manjeera River",
      "water_te": "మంజీరా నది",
      "fertilizers": "DAP, Potash",
      "fertilizers_te": "డి.ఏ.పీ, పొటాష్",
      "irrigation": "Canals, Tanks",
      "irrigation_te": "కాలువలు, చెరువులు"
    },
    "Medchal Malkajgiri": {
      "name": "Medchal Malkajgiri",
      "telugu": "మెద్చల్ మల్కాజిగిరి",
      "rainfall": "800 mm",
      "rainfall_te": "800 మి.మీ.",
      "temperature": "32°C",
      "temperature_te": "32 డిగ్రీల సెల్సియస్",
      "soil": "Red sandy soil",
      "soil_te": "ఎరుపు ముంచి మట్టి",
      "crops": "Vegetables, Flowers",
      "crops_te": "కూరగాయలు, పుష్పాలు",
      "humidity": "58%",
      "humidity_te": "58%",
      "ph": "6.4",
      "ph_te": "6.4",
      "water": "Himayat Sagar, Osmansagar",
      "water_te": "హిమాయత్ సాగర్, ఉస్మాన్ సాగర్",
      "fertilizers": "Compost, Urea",
      "fertilizers_te": "జైవ ఎరువులు, యూరియా",
      "irrigation": "Drip, Bore well",
      "irrigation_te": "డ్రిప్, బోర్ వెల్"
    },
    "Mulugu": {
      "name": "Mulugu",
      "telugu": "ములుగు",
      "rainfall": "1100 mm",
      "rainfall_te": "1100 మి.మీ.",
      "temperature": "27°C",
      "temperature_te": "27 డిగ్రీల సెల్సియస్",
      "soil": "Red and black soil",
      "soil_te": "ఎరుపు మరియు నల్ల మట్టి",
      "crops": "Paddy, Cotton, Turmeric",
      "crops_te": "బియ్యం, పత్తి, పసుపు",
      "humidity": "70%",
      "humidity_te": "70%",
      "ph": "6.6",
      "ph_te": "6.6",
      "water": "Godavari River",
      "water_te": "గోదావరి నది",
      "fertilizers": "Urea, DAP",
      "fertilizers_te": "యూరియా, డి.ఏ.పీ",
      "irrigation": "Canals, Tanks",
      "irrigation_te": "కాలువలు, చెరువులు"
    },
    "Nagarkurnool": {
      "name": "Nagarkurnool",
      "telugu": "నాగర్ కర్నూల్",
      "rainfall": "700 mm",
      "rainfall_te": "700 మి.మీ.",
      "temperature": "31°C",
      "temperature_te": "31 డిగ్రీల సెల్సియస్",
      "soil": "Red loamy soil",
      "soil_te": "ఎరుపు లోమీ మట్టి",
      "crops": "Groundnut, Jowar, Pulses",
      "crops_te": "వేరుశెనగ, జొన్న, పప్పులు",
      "humidity": "55%",
      "humidity_te": "55%",
      "ph": "6.3",
      "ph_te": "6.3",
      "water": "Krishna River",
      "water_te": "కృష్ణా నది",
      "fertilizers": "DAP, Organic manure",
      "fertilizers_te": "డి.ఏ.పీ, సేంద్రీయ ఎరువులు",
      "irrigation": "Bore wells, Canal",
      "irrigation_te": "బోర్ వెల్లు, కాలువ"
    },
    "Nalgonda": {
      "name": "Nalgonda",
      "telugu": "నల్గొండ",
      "rainfall": "850 mm",
      "rainfall_te": "850 మి.మీ.",
      "temperature": "30°C",
      "temperature_te": "30 డిగ్రీల సెల్సియస్",
      "soil": "Red sandy soil",
      "soil_te": "ఎరుపు ముంచి మట్టి",
      "crops": "Paddy, Cotton, Chillies",
      "crops_te": "బియ్యం, పత్తి, మిరప",
      "humidity": "60%",
      "humidity_te": "60%",
      "ph": "6.5",
      "ph_te": "6.5",
      "water": "Krishna River",
      "water_te": "కృష్ణా నది",
      "fertilizers": "Potash, Urea",
      "fertilizers_te": "పొటాష్, యూరియా",
      "irrigation": "Canals, Bore wells",
      "irrigation_te": "కాలువలు, బోర్ వెల్లు"
    },
      "Nalgonda": {
        "name": "Nalgonda",
        "telugu": "నల్గొండ",
        "rainfall": "850 mm",
        "rainfall_te": "850 మి.మీ.",
        "temperature": "31°C",
        "temperature_te": "31 డిగ్రీల సెల్సియస్",
        "soil": "Red sandy loam",
        "soil_te": "ఎరుపు ముంచి లోమ్ మట్టి",
        "crops": "Cotton, Paddy, Groundnut",
        "crops_te": "పత్తి, బియ్యం, వేరుశెనగ",
        "humidity": "60%",
        "humidity_te": "60%",
        "ph": "6.4",
        "ph_te": "6.4",
        "water": "Musi River",
        "water_te": "మూసి నది",
        "fertilizers": "Urea, Potash",
        "fertilizers_te": "యూరియా, పొటాష్",
        "irrigation": "Canals, Bore wells",
        "irrigation_te": "కాలువలు, బోర్ వెల్లు"
      },
      "Narayanpet": {
        "name": "Narayanpet",
        "telugu": "నారాయణపేట్",
        "rainfall": "650 mm",
        "rainfall_te": "650 మి.మీ.",
        "temperature": "32°C",
        "temperature_te": "32 డిగ్రీల సెల్సియస్",
        "soil": "Red and black soils",
        "soil_te": "ఎరుపు మరియు నల్ల మట్టి",
        "crops": "Jowar, Bajra, Cotton",
        "crops_te": "జొన్న, సజ్జ, పత్తి",
        "humidity": "52%",
        "humidity_te": "52%",
        "ph": "6.2",
        "ph_te": "6.2",
        "water": "Local tanks",
        "water_te": "చెరువులు",
        "fertilizers": "Urea, Compost",
        "fertilizers_te": "యూరియా, కాంపోస్ట్",
        "irrigation": "Bore wells, Tanks",
        "irrigation_te": "బోర్ వెల్లు, చెరువులు"
      },
      "Nirmal": {
        "name": "Nirmal",
        "telugu": "నిర్మల్",
        "rainfall": "1050 mm",
        "rainfall_te": "1050 మి.మీ.",
        "temperature": "27°C",
        "temperature_te": "27 డిగ్రీల సెల్సియస్",
        "soil": "Black cotton soil",
        "soil_te": "నల్లపాటి మట్టి",
        "crops": "Paddy, Maize, Turmeric",
        "crops_te": "బియ్యం, మక్కజొన్న, పసుపు",
        "humidity": "72%",
        "humidity_te": "72%",
        "ph": "6.7",
        "ph_te": "6.7",
        "water": "Godavari River",
        "water_te": "గోదావరి నది",
        "fertilizers": "DAP, Urea",
        "fertilizers_te": "డి.ఏ.పీ, యూరియా",
        "irrigation": "Canals, Bore wells",
        "irrigation_te": "కాలువలు, బోర్ వెల్లు"
      },
      "Nizamabad": {
        "name": "Nizamabad",
        "telugu": "నిజామాబాద్",
        "rainfall": "980 mm",
        "rainfall_te": "980 మి.మీ.",
        "temperature": "29°C",
        "temperature_te": "29 డిగ్రీల సెల్సియస్",
        "soil": "Black and red soils",
        "soil_te": "నల్ల మరియు ఎరుపు మట్టి",
        "crops": "Paddy, Sugarcane, Turmeric",
        "crops_te": "బియ్యం, చెరకు, పసుపు",
        "humidity": "68%",
        "humidity_te": "68%",
        "ph": "6.6",
        "ph_te": "6.6",
        "water": "Godavari River",
        "water_te": "గోదావరి నది",
        "fertilizers": "Urea, Organic",
        "fertilizers_te": "యూరియా, సేంద్రీయ",
        "irrigation": "Canals, Bore wells",
        "irrigation_te": "కాలువలు, బోర్ వెల్లు"
      },
      "Peddapalli": {
        "name": "Peddapalli",
        "telugu": "పెద్దపల్లి",
        "rainfall": "970 mm",
        "rainfall_te": "970 మి.మీ.",
        "temperature": "28°C",
        "temperature_te": "28 డిగ్రీల సెల్సియస్",
        "soil": "Black soil",
        "soil_te": "నల్లపాటి మట్టి",
        "crops": "Paddy, Cotton, Redgram",
        "crops_te": "బియ్యం, పత్తి, ఎర్రమినుము",
        "humidity": "66%",
        "humidity_te": "66%",
        "ph": "6.8",
        "ph_te": "6.8",
        "water": "Godavari River",
        "water_te": "గోదావరి నది",
        "fertilizers": "Urea, Potash",
        "fertilizers_te": "యూరియా, పొటాష్",
        "irrigation": "Canals, Bore wells",
        "irrigation_te": "కాలువలు, బోర్ వెల్లు"
      },
      "Rajanna Sircilla": {
        "name": "Rajanna Sircilla",
        "telugu": "రాజన్న సిరిసిల్లా",
        "rainfall": "880 mm",
        "rainfall_te": "880 మి.మీ.",
        "temperature": "29°C",
        "temperature_te": "29 డిగ్రీల సెల్సియస్",
        "soil": "Red sandy soil",
        "soil_te": "ఎరుపు ముంచి మట్టి",
        "crops": "Cotton, Paddy, Maize",
        "crops_te": "పత్తి, బియ్యం, మక్కజొన్న",
        "humidity": "62%",
        "humidity_te": "62%",
        "ph": "6.5",
        "ph_te": "6.5",
        "water": "Manair River",
        "water_te": "మనెయిర్ నది",
        "fertilizers": "Urea, DAP",
        "fertilizers_te": "యూరియా, డి.ఏ.పీ",
        "irrigation": "Canals, Bore wells",
        "irrigation_te": "కాలువలు, బోర్ వెల్లు"
      },
      "Rangareddy": {
        "name": "Rangareddy",
        "telugu": "రంగారెడ్డి",
        "rainfall": "820 mm",
        "rainfall_te": "820 మి.మీ.",
        "temperature": "31°C",
        "temperature_te": "31 డిగ్రీల సెల్సియస్",
        "soil": "Red loamy soil",
        "soil_te": "ఎరుపు లోమీ మట్టి",
        "crops": "Vegetables, Flowers, Paddy",
        "crops_te": "కూరగాయలు, పుష్పాలు, బియ్యం",
        "humidity": "58%",
        "humidity_te": "58%",
        "ph": "6.4",
        "ph_te": "6.4",
        "water": "Himayat Sagar",
        "water_te": "హిమాయత్ సాగర్",
        "fertilizers": "Compost, Urea",
        "fertilizers_te": "జైవ ఎరువులు, యూరియా",
        "irrigation": "Drip, Tanks",
        "irrigation_te": "డ్రిప్, చెరువులు"
      },
      "Sangareddy": {
        "name": "Sangareddy",
        "telugu": "సంగారెడ్డి",
        "rainfall": "860 mm",
        "rainfall_te": "860 మి.మీ.",
        "temperature": "30°C",
        "temperature_te": "30 డిగ్రీల సెల్సియస్",
        "soil": "Red and black soils",
        "soil_te": "ఎరుపు మరియు నల్ల మట్టి",
        "crops": "Sugarcane, Maize, Paddy",
        "crops_te": "చెరకు, మక్కజొన్న, బియ్యం",
        "humidity": "60%",
        "humidity_te": "60%",
        "ph": "6.6",
        "ph_te": "6.6",
        "water": "Manjeera River",
        "water_te": "మంజీరా నది",
        "fertilizers": "Urea, Organic",
        "fertilizers_te": "యూరియా, సేంద్రీయ",
        "irrigation": "Canals, Bore wells",
        "irrigation_te": "కాలువలు, బోర్ వెల్లు"
      },
      "Siddipet": {
        "name": "Siddipet",
        "telugu": "సిద్ధిపేట",
        "rainfall": "870 mm",
        "rainfall_te": "870 మి.మీ.",
        "temperature": "30°C",
        "temperature_te": "30 డిగ్రీల సెల్సియస్",
        "soil": "Red sandy loam",
        "soil_te": "ఎరుపు ముంచి లోమ్ మట్టి",
        "crops": "Paddy, Pulses, Cotton",
        "crops_te": "బియ్యం, పప్పు ధాన్యాలు, పత్తి",
        "humidity": "63%",
        "humidity_te": "63%",
        "ph": "6.5",
        "ph_te": "6.5",
        "water": "Kakatiya Canal",
        "water_te": "కాకతీయ కాలువ",
        "fertilizers": "Urea, Potash",
        "fertilizers_te": "యూరియా, పొటాష్",
        "irrigation": "Canals, Tanks",
        "irrigation_te": "కాలువలు, చెరువులు"
      },
      "Suryapet": {
        "name": "Suryapet",
        "telugu": "సూర్యాపేట",
        "rainfall": "840 mm",
        "rainfall_te": "840 మి.మీ.",
        "temperature": "31°C",
        "temperature_te": "31 డిగ్రీల సెల్సియస్",
        "soil": "Red sandy soil",
        "soil_te": "ఎరుపు ముంచి మట్టి",
        "crops": "Paddy, Cotton, Pulses",
        "crops_te": "బియ్యం, పత్తి, పప్పుధాన్యాలు",
        "humidity": "61%",
        "humidity_te": "61%",
        "ph": "6.4",
        "ph_te": "6.4",
        "water": "Musi River",
        "water_te": "మూసి నది",
        "fertilizers": "Urea, DAP",
        "fertilizers_te": "యూరియా, డి.ఏ.పీ",
        "irrigation": "Canals, Tanks",
        "irrigation_te": "కాలువలు, చెరువులు"
      },
      "Vikarabad": {
        "name": "Vikarabad",
        "telugu": "వికారాబాద్",
        "rainfall": "860 mm",
        "rainfall_te": "860 మి.మీ.",
        "temperature": "30°C",
        "temperature_te": "30 డిగ్రీల సెల్సియస్",
        "soil": "Red sandy soil",
        "soil_te": "ఎరుపు ముంచి మట్టి",
        "crops": "Maize, Cotton, Vegetables",
        "crops_te": "మక్కజొన్న, పత్తి, కూరగాయలు",
        "humidity": "64%",
        "humidity_te": "64%",
        "ph": "6.6",
        "ph_te": "6.6",
        "water": "Kagna River",
        "water_te": "కాగ్నా నది",
        "fertilizers": "Urea, Compost",
        "fertilizers_te": "యూరియా, కాంపోస్ట్",
        "irrigation": "Canals, Bore wells",
        "irrigation_te": "కాలువలు, బోర్ వెల్లు"
      },
      "Wanaparthy": {
        "name": "Wanaparthy",
        "telugu": "వనపర్తి",
        "rainfall": "700 mm",
        "rainfall_te": "700 మి.మీ.",
        "temperature": "32°C",
        "temperature_te": "32 డిగ్రీల సెల్సియస్",
        "soil": "Red loamy soil",
        "soil_te": "ఎరుపు లోమీ మట్టి",
        "crops": "Jowar, Bajra, Pulses",
        "crops_te": "జొన్న, సజ్జ, పప్పుధాన్యాలు",
        "humidity": "56%",
        "humidity_te": "56%",
        "ph": "6.3",
        "ph_te": "6.3",
        "water": "Krishna River",
        "water_te": "కృష్ణా నది",
        "fertilizers": "DAP, Organic",
        "fertilizers_te": "డి.ఏ.పీ, సేంద్రీయ",
        "irrigation": "Bore wells, Canal",
        "irrigation_te": "బోర్ వెల్లు, కాలువ"
      },
      "Warangal": {
        "name": "Warangal",
        "telugu": "వరంగల్",
        "rainfall": "950 mm",
        "rainfall_te": "950 మి.మీ.",
        "temperature": "30°C",
        "temperature_te": "30 డిగ్రీల సెల్సియస్",
        "soil": "Red sandy loam",
        "soil_te": "ఎరుపు ముంచి లోమ్ మట్టి",
        "crops": "Paddy, Cotton, Maize",
        "crops_te": "బియ్యం, పత్తి, మక్కజొన్న",
        "humidity": "67%",
        "humidity_te": "67%",
        "ph": "6.6",
        "ph_te": "6.6",
        "water": "Godavari Canal",
        "water_te": "గోదావరి కాలువ",
        "fertilizers": "Urea, DAP",
        "fertilizers_te": "యూరియా, డి.ఏ.పీ",
        "irrigation": "Canals, Bore wells",
        "irrigation_te": "కాలువలు, బోర్ వెల్లు"
      }
    };
    
  